language: python
python:
    - "2.7"

# Cache PlatformIO packages using containers
sudo: false
cache:
    directories:
        - "~/.platformio"


install:
    - pip install -U platformio

script:
    - make
    - make test
