language: python
python:
    - "2.7"

# Cache PlatformIO packages using containers
sudo: false
cache:
    directories:
        - "~/.platformio"


install:
    - pip install -U platformio

script:
    - make
    - make test

notifications:
    irc:
        channels:
            - "irc.freenode.net#roomservice"
        on_success: change
        on_failure: always
        use_notice: true
        skip_join: true

